name: Dependency Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: juice_shop

    - name: Run npm audits
      run: |
        npm audit --json > audit-report.json
        cat juice_shop/audit-report.json
      working-directory: juice_shop
      continue-on-error: true

    - name: Upload audit reports
      uses: actions/upload-artifact@v4
      with:
        name: audit-report
        path: juice_shop/audit-report.json

    - name: Print vulnerability summary
      id: summary
      run: |
        echo "================== Vulnerability Summary =================="
        if [ -s juice_shop/audit-report.json ]; then
          SUMMARY=$(jq -r '
            [
              .vulnerabilities[]? | 
              {package: .name, severity: .severity, title: .title, url: .url}
            ] 
            | sort_by(.severity) 
            | .[] 
            | "Package: \(.package)\nSeverity: \(.severity)\nIssue: \(.title)\nURL: \(.url)\n-------------------------"
          ' juice_shop/audit-report.json)
        else
          echo "No vulnerabilities found."
        fi

        printf "%s\n" "$SUMMARY"
        SUMMARY="${SUMMARY//'%'/'%25'}"
        SUMMARY="${SUMMARY//$'\n'/'%0A'}"
        SUMMARY="${SUMMARY//$'\r'/'%0D'}"
        echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

    - name: Comment on Pull Request
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## 🛡 Dependency Vulnerability Report
          
          ${{ steps.summary.outputs.summary }}

    - name: Fail if high severity found
      run: |
        HIGH=$(jq '.metadata.vulnerabilities.high' juice_shop/audit-report.json)
        if [ "$HIGH" -gt 0 ]; then
          echo "High severity vulnerabilities detected!"
          exit 1
        else
          echo "No high severity vulnerabilities."
        fi
      shell: bash

    - name: Notify Slack on failure
      if: failure()  # Only runs when the previous job fails
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        PAYLOAD=$(jq -n --arg repo "${{ github.repository }}" \
                         --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                         --arg branch "${{ github.ref_name }}" \
                         --arg summary "${{ env.summary }}" \
        '{
          "attachments": [
            {
              "color": "#ff0000",
              "title": "⚠️ Dependency Check Failed",
              "fields": [
                {"title": "Repository", "value": $repo, "short": true},
                {"title": "Branch", "value": $branch, "short": true},
                {"title": "Details", "value": $summary, "short": false}
              ],
              "actions": [
                {
                  "type": "button",
                  "text": "View Workflow Run",
                  "url": $url
                }
              ]
            }
          ]
        }')

        curl -X POST -H 'Content-type: application/json' \
          --data "$PAYLOAD" \
          "$SLACK_WEBHOOK_URL"


