name: Semgrep SAST Scan

on:
  push:
    #branches: [ "main" ]
    branches: [ "semgrep-pipeline" ]
  pull_request:
    #branches: [ "main" ]
    branches: [ "semgrep-pipeline" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          semgrep --config=auto --exclude node_modules

      # OPTIONAL: Upload report as artifact
      - name: Save Semgrep Report
        run: semgrep --config=auto --json --exclude node_modules > semgrep-report.json

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
